version: '3'
services:
  server:
    build: ./server
    command: npm start
    volumes:
     - ./server:/usr/app/
    ports:
     - "40274:40274"
    depends_on:
     - mongo
    environment:
     EVENDEMY_DATABASE_URL: mongodb://mongo/mydb
  mongo:
    image: "mongo"
    volumes:
     - ./.mongoData:/data/db
